import json


def render(data):
    payload = json.dumps(data, separators=(",", ":"))
    html = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SolvX — 3D Ocean Explorer</title>
<style>
*{box-sizing:border-box}html,body,#app{margin:0;width:100%;height:100%;overflow:hidden;background:#06131d}body{font-family:Inter,system-ui,sans-serif;color:#dcebf0}canvas{display:block;width:100%;height:100%}
#app{position:fixed;inset:0}.glass{background:rgba(5,19,28,.78);border:1px solid rgba(130,205,220,.18);box-shadow:0 14px 40px rgba(0,0,0,.28);backdrop-filter:blur(16px)}
#top{position:absolute;z-index:10;top:14px;left:14px;right:14px;display:flex;justify-content:space-between;align-items:center;pointer-events:none}.brand{padding:9px 13px;border-radius:11px;pointer-events:auto}.brand b{font-size:14px;letter-spacing:.14em}.brand small{display:block;color:#7898a2;font-size:8px;margin-top:3px;letter-spacing:.08em}.tools{display:flex;gap:4px;padding:5px;border-radius:11px;pointer-events:auto}.btn{border:0;border-radius:7px;padding:8px 10px;background:transparent;color:#8ca7b0;font-size:9px;cursor:pointer}.btn:hover,.btn.active{background:#103744;color:#d8f6fa}
#vars{position:absolute;z-index:12;left:14px;top:78px;width:235px;max-height:calc(100vh - 150px);overflow:auto;padding:13px;border-radius:13px}.title{font-size:9px;color:#6f8d97;letter-spacing:.14em;text-transform:uppercase;margin-bottom:9px}.current{padding:9px;border-radius:8px;background:rgba(91,211,233,.09);border:1px solid rgba(91,211,233,.16);margin-bottom:11px}.current b{font-size:12px}.current small{display:block;color:#71909a;font-size:8px;margin-top:3px}.vlist{display:grid;gap:3px}.v{width:100%;display:grid;grid-template-columns:28px 1fr auto;gap:5px;align-items:center;border:1px solid transparent;border-radius:7px;background:transparent;padding:8px;text-align:left;color:#91aab3;cursor:pointer}.v:hover{background:rgba(255,255,255,.035)}.v.active{background:rgba(91,211,233,.1);border-color:rgba(91,211,233,.17);color:#e3f5f8}.v i{font-style:normal;color:#5f8995;font-size:9px}.v.active i{color:#5bd3e9}.v small{font-size:8px;color:#55717b}.sep{height:1px;background:rgba(130,205,220,.1);margin:12px 0}.row{display:flex;align-items:center;justify-content:space-between;color:#718c96;font-size:8px;margin-bottom:6px}.range{width:100%;accent-color:#5bd3e9}.modes{display:grid;grid-template-columns:1fr 1fr;gap:4px}.mode{border:1px solid rgba(130,205,220,.12);background:#0a202b;color:#79939c;border-radius:6px;padding:7px;font-size:8px;cursor:pointer}.mode.active{border-color:#398d9e;color:#d7f5f8;background:#0d3541}
#legend{position:absolute;z-index:9;right:15px;bottom:78px;width:210px;padding:10px;border-radius:10px}.legend-head{display:flex;justify-content:space-between;font-size:8px;color:#7f9aa3}.bar{height:8px;border-radius:4px;margin:7px 0 4px;background:linear-gradient(90deg,#171f9e,#21a9d4,#e9e64d,#ef5b32)}.ends{display:flex;justify-content:space-between;color:#67828b;font-size:7px;font-family:monospace}
#timeline{position:absolute;z-index:15;left:0;right:0;bottom:0;padding:11px 24px 10px;border-top:1px solid rgba(130,205,220,.14);background:rgba(4,14,21,.9);backdrop-filter:blur(14px)}.timehead{display:flex;justify-content:space-between;align-items:center;font-size:8px;color:#6c8993}.timehead b{font-size:10px;color:#d9edf0}.time{width:100%;accent-color:#5bd3e9;cursor:pointer}.ticks{display:flex;justify-content:space-between;color:#405b65;font:7px monospace}.status{position:absolute;right:14px;top:72px;padding:7px 9px;border-radius:8px;font:8px monospace;color:#78949d;z-index:10}.hint{position:absolute;left:14px;bottom:70px;color:#607d87;font:7px monospace;z-index:9}.loading{position:absolute;inset:0;z-index:50;display:grid;place-items:center;background:#06131d}.loading b{letter-spacing:.18em}.loading small{display:block;margin-top:6px;color:#63818c;font-size:8px;text-align:center}
@media(max-width:800px){#vars{width:205px;left:8px;top:66px}.tools .btn:nth-child(n+4){display:none}.brand{left:8px}.status{top:62px}.hint{display:none}}
</style></head><body><div id="app"><div class="loading" id="loading"><div><b>SOLVX</b><small>CONNECTING TO OCEAN DATA API</small></div></div>
<div id="top"><div class="brand glass"><b>SOLVX</b><small>BAY OF BENGAL · 3D OCEAN EXPLORER</small></div><div class="tools glass"><button class="btn active" data-view="3d">3D</button><button class="btn" data-view="top">TOP</button><button class="btn" data-view="profile">PROFILE</button><button class="btn" data-view="under">UNDER</button><button class="btn" id="full">FULLSCREEN</button></div></div>
<aside id="vars" class="glass"><div class="title">Ocean variables</div><div class="current"><b id="activeName">Loading…</b><small id="activeMeta">Backend variable metadata</small></div><div class="vlist" id="vlist"></div><div class="sep"></div><div class="title">Depth</div><div class="row"><span>Visible depth</span><b id="depthText">100%</b></div><input class="range" id="depth" type="range" min="0.02" max="1" step="0.01" value="1"><div class="row"><span>Surface</span><span>Full depth</span></div><div class="sep"></div><div class="title">View mode</div><div class="modes"><button class="mode active" data-view="3d">VOLUME</button><button class="mode" data-view="profile">SLICE</button><button class="mode" data-view="top">SURFACE</button><button class="mode" data-view="under">UNDER</button></div></aside>
<div id="status" class="status glass">API: connecting</div><div id="hint" class="hint">Drag to orbit · wheel to zoom · 1–4 views · R reset</div>
<div id="legend" class="glass"><div class="legend-head"><span id="legendName">Variable</span><span id="legendUnits">—</span></div><div class="bar"></div><div class="ends"><span id="legendMin">—</span><span id="legendMax">—</span></div></div>
<div id="timeline"><div class="timehead"><span>TIME</span><b id="dateLabel">—</b><span id="dateRange">—</span></div><input id="time" class="time" type="range" min="0" max="0" value="0"><div class="ticks"><span id="tick0">—</span><span id="tick1">—</span><span id="tick2">—</span><span id="tick3">—</span><span id="tick4">—</span></div></div></div>
<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/"}}</script>
<script type="module">
import * as THREE from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const D=__PAYLOAD__;const API=window.SOLVX_API||'http://127.0.0.1:8000';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x06131d);scene.fog=new THREE.FogExp2(0x06131d,.0008);
const cam=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,6000);cam.position.set(520,-650,480);
const ren=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});ren.setPixelRatio(Math.min(devicePixelRatio,2));ren.setSize(innerWidth,innerHeight);ren.outputColorSpace=THREE.SRGBColorSpace;document.getElementById('app').appendChild(ren.domElement);
const ctl=new OrbitControls(cam,ren.domElement);ctl.enableDamping=true;ctl.dampingFactor=.06;ctl.screenSpacePanning=true;ctl.minDistance=35;ctl.maxDistance=2600;ctl.target.set(0,0,-80);
scene.add(new THREE.HemisphereLight(0x9bd8e2,0x17232a,1.15));const sun=new THREE.DirectionalLight(0xc9f5ff,2.1);sun.position.set(-350,-420,900);scene.add(sun);
const G={volume:new THREE.Group(),surface:new THREE.Group(),terrain:new THREE.Group(),land:new THREE.Group(),coast:new THREE.Group(),eez:new THREE.Group(),particles:new THREE.Group()};Object.values(G).forEach(g=>scene.add(g));
const terrainMat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.9,side:THREE.DoubleSide});
(function(){const xs=D.terrain.x,ys=D.terrain.y,raw=D.terrain.rawDepthKm,nx=xs.length,ny=ys.length,pos=new Float32Array(nx*ny*3),col=new Float32Array(nx*ny*3),ind=[];for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const k=j*nx+i,o=k*3,d=raw[j][i];pos[o]=xs[i];pos[o+1]=ys[j];pos[o+2]=Number.isFinite(d)?-d*70:0;const t=Number.isFinite(d)?Math.min(1,d/Math.max(1,D.terrain.maxDepthKm)):0;col[o]=.67-.27*t;col[o+1]=.5-.21*t;col[o+2]=.31-.14*t}for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const a=j*nx+i,b=a+1,c=a+nx,d=c+1;if([raw[j][i],raw[j][i+1],raw[j+1][i],raw[j+1][i+1]].every(Number.isFinite))ind.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));g.setIndex(ind);g.computeVertexNormals();G.terrain.add(new THREE.Mesh(g,terrainMat))})();
function poly(p){if(!p.vertices?.length||!p.triangles?.length)return;const v=[],ix=[];p.vertices.forEach(q=>v.push(q[0],q[1],0));p.triangles.forEach(t=>ix.push(t[0],t[1],t[2]));const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(ix);g.computeVertexNormals();G.land.add(new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x405f47,roughness:.95})))}D.land.forEach(poly);D.islands.forEach(poly);
function lines(parts,color,z=0){parts.forEach(p=>{if(p.length<2)return;G.coast.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p.map(q=>new THREE.Vector3(q[0],q[1],z))),new THREE.LineBasicMaterial({color,transparent:true,opacity:.8})))})}lines(D.coast,0x8db9c2,.2);lines(D.landBoundary,0x73969e,.25);lines(D.islandCoast,0x73969e,.25);D.eez.forEach(p=>{if(p.length>1)G.eez.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p.map(q=>new THREE.Vector3(q[0],q[1],.3))),new THREE.LineBasicMaterial({color:0xd39a2f,transparent:true,opacity:.9})))})
const surface=new THREE.Mesh(new THREE.PlaneGeometry((D.bounds[1]-D.bounds[0])*111.32*Math.cos((D.bounds[2]+D.bounds[3])*Math.PI/360), (D.bounds[3]-D.bounds[2])*111.32,100,80),new THREE.MeshPhysicalMaterial({color:0x14758a,transparent:true,opacity:.16,roughness:.06,metalness:0,transmission:.15,depthWrite:false,side:THREE.DoubleSide}));surface.rotation.x=0;surface.position.z=.5;G.surface.add(surface);
let volumeMesh=null,volumeTex=null,scalarRange=[0,1],visibleCut=1,active={};let mode='3d';
const palette=`vec3 cmap(float t){vec3 a=vec3(0.04,0.08,0.55),b=vec3(0.02,0.65,0.88),c=vec3(0.98,0.88,0.18),d=vec3(0.86,0.10,0.04);if(t<.45)return mix(a,b,t/.45);if(t<.78)return mix(b,c,(t-.45)/.33);return mix(c,d,(t-.78)/.22);}`;
const vs=`varying vec3 vPos;void main(){vPos=position*.5+.5;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
const fs=`precision highp float;precision highp sampler3D;varying vec3 vPos;uniform sampler3D uVolume;uniform vec2 uRange;uniform float uCut;uniform vec3 uCamera;${palette}void main(){vec3 ray=normalize(vPos-uCamera);vec3 inv=1./ray;vec3 t0=(vec3(0.)-vPos)*inv,t1=(vec3(1.)-vPos)*inv,lo=min(t0,t1),hi=max(t0,t1);float en=max(max(lo.x,lo.y),lo.z),ex=min(min(hi.x,hi.y),hi.z);if(ex<=en)discard;vec3 p=vPos+ray*max(en,0.);vec4 a=vec4(0.);for(int i=0;i<150;i++){if(any(lessThan(p,vec3(0.)))||any(greaterThan(p,vec3(1.))))break;float df=1.-p.y;if(df<=uCut){float raw=texture(uVolume,p).r;if(raw>-999.){float t=clamp((raw-uRange.x)/max(.000001,uRange.y-uRange.x),0.,1.);float al=.038;vec3 c=cmap(t);a.rgb+=(1.-a.a)*al*c;a.a+=(1.-a.a)*al;if(a.a>.94)break;}}p+=ray/120.;}if(a.a<.006)discard;gl_FragColor=a;}`;
function clearVolume(){if(volumeMesh){G.volume.remove(volumeMesh);volumeMesh.geometry.dispose();volumeMesh.material.dispose();}if(volumeTex)volumeTex.dispose();volumeMesh=null;volumeTex=null}
function nestedGrid(payload){const dims=(payload.dimensions||[]).map(String),shape=(payload.shape||[]).map(Number),zi=dims.indexOf('depth'),yi=dims.indexOf('latitude'),xi=dims.indexOf('longitude');if(yi<0||xi<0)return null;const nx=shape[xi],ny=shape[yi],nz=zi>=0?shape[zi]:1,count=nx*ny*nz;if(!nx||!ny||count>450000)return null;const values=new Float32Array(count);let min=Infinity,max=-Infinity;const read=(node,ids)=>{for(const id of ids){if(!Array.isArray(node))return NaN;node=node[id]}return Number(node)};for(let z=0;z<nz;z++)for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const ids=new Array(dims.length).fill(0);if(zi>=0)ids[zi]=z;ids[yi]=y;ids[xi]=x;const v=read(payload.data,ids),i=x+nx*(y+ny*z);values[i]=Number.isFinite(v)?v:-9999;if(Number.isFinite(v)){min=Math.min(min,v);max=Math.max(max,v)}}if(!Number.isFinite(min))return null;return{values,nx,ny,nz,min,max}}
function installVolume(grid){clearVolume();scalarRange=[grid.min,grid.max];volumeTex=new THREE.Data3DTexture(grid.values,grid.nx,grid.ny,grid.nz);volumeTex.format=THREE.RedFormat;volumeTex.type=THREE.FloatType;volumeTex.minFilter=THREE.LinearFilter;volumeTex.magFilter=THREE.LinearFilter;volumeTex.unpackAlignment=1;volumeTex.needsUpdate=true;const box=new THREE.BoxGeometry(900,420,700);const mat=new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,transparent:true,side:THREE.BackSide,depthWrite:false,uniforms:{uVolume:{value:volumeTex},uRange:{value:new THREE.Vector2(grid.min,grid.max)},uCut:{value:visibleCut},uCamera:{value:new THREE.Vector3(.5,.5,1.5)}},vertexShader:vs,fragmentShader:fs});volumeMesh=new THREE.Mesh(box,mat);volumeMesh.position.y=-210;G.volume.add(volumeMesh);updateLegend()}
function updateLegend(){document.getElementById('legendName').textContent=active.long_name||active.name||'Variable';document.getElementById('legendUnits').textContent=active.units||'—';document.getElementById('legendMin').textContent=Number.isFinite(scalarRange[0])?scalarRange[0].toFixed(2):'—';document.getElementById('legendMax').textContent=Number.isFinite(scalarRange[1])?scalarRange[1].toFixed(2):'—';document.getElementById('activeName').textContent=active.long_name||active.name||'Loading…';document.getElementById('activeMeta').textContent=`${active.units||'unknown units'} · ${active.dimensions?.join(' × ')||'backend data'}`}
function cameraLocal(){if(!volumeMesh)return;const p=volumeMesh.worldToLocal(cam.position.clone());p.x=p.x/900+.5;p.y=p.y/420+.5;p.z=p.z/700+.5;volumeMesh.material.uniforms.uCamera.value.copy(p);volumeMesh.material.uniforms.uCut.value=visibleCut}
const views={3d:[520,-650,480],top:[0,0,1150],profile:[850,-30,180],under:[420,-520,-420]};function setView(v){mode=v;const p=views[v];cam.position.set(...p);ctl.target.set(0,0,v==='under'?-160:-100);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));}
async function getJson(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text());return r.json()}
let datasets=[],catalog=[],selectedFile='',selectedVar='',dates=[];
function labelVariable(v){const s=`${v.name} ${v.long_name||''} ${v.standard_name||''}`.toLowerCase();if(/temperature|thetao/.test(s))return['TEMP','Temperature'];if(/salin/.test(s))return['SAL','Salinity'];if(/current|velocity|uo|vo/.test(s))return['CUR','Currents'];if(/sea.*surface.*height|ssh|sla/.test(s))return['SSH','Sea surface height'];if(/wave/.test(s))return['WAV','Wave height'];if(/wind/.test(s))return['WND','Wind'];if(/chlorophyll|chl/.test(s))return['CHL','Chlorophyll-a'];if(/oxygen|o2/.test(s))return['O2','Oxygen'];if(/ph|acid/.test(s))return['pH','Acidity / pH'];if(/biomass/.test(s))return['BIO','Biomass'];return['VAR',v.long_name||v.name]}
function renderCatalog(){const el=document.getElementById('vlist');el.innerHTML='';const seen=new Set();catalog.forEach(item=>{const [code,label]=labelVariable(item);const key=label;if(seen.has(key))return;seen.add(key);const b=document.createElement('button');b.className='v';b.innerHTML=`<i>${code}</i><span>${label}</span><small>${item.units||''}</small>`;b.onclick=()=>selectVariable(item);el.appendChild(b)})}
async function selectVariable(item){active=item;selectedFile=item.file;selectedVar=item.name;document.querySelectorAll('.v').forEach(x=>x.classList.remove('active'));renderCatalog();setStatus('Loading '+(item.long_name||item.name));await loadData();}
function setStatus(s){document.getElementById('status').textContent=s}
async function loadData(){try{const end=dates.length?dates[Math.min(+document.getElementById('time').value,dates.length-1)]:'';const q=new URLSearchParams({file:selectedFile,variable:selectedVar,lat_min:String(D.bounds[2]),lat_max:String(D.bounds[3]),lon_min:String(D.bounds[0]),lon_max:String(D.bounds[1]),depth_min:'0.49',depth_max:String(D.terrain.maxDepthKm*1000),time_start:end,time_end:end});const p=await getJson(`${API}/data/region/array?${q}`);const grid=nestedGrid(p);if(!grid)throw Error('Backend did not return a usable 3D/2D grid');installVolume(grid);setStatus(`API: ${selectedVar} · ${end||'latest'}`)}catch(e){setStatus('API error: '+e.message);console.error(e)}}
function setupDates(){const all=new Set();datasets.forEach(d=>{if(d.time_start)all.add(d.time_start)});if(!dates.length){const start=new Date('2026-08-01T00:00:00Z'),end=new Date('2026-09-09T00:00:00Z');for(let t=start;t<=end;t.setUTCDate(t.getUTCDate()+1))dates.push(t.toISOString().slice(0,10))}const t=document.getElementById('time');t.max=Math.max(0,dates.length-1);t.value=dates.length-1;document.getElementById('dateRange').textContent=`${dates[0]} → ${dates[dates.length-1]}`;[0,.25,.5,.75,1].forEach((p,i)=>document.getElementById('tick'+i).textContent=dates[Math.min(dates.length-1,Math.round((dates.length-1)*p))]);updateDate()}
function updateDate(){const d=dates[+document.getElementById('time').value]||'—';document.getElementById('dateLabel').textContent=d}
async function init(){try{datasets=(await getJson(`${API}/datasets`)).datasets||[];for(const d of datasets){for(const name of d.variables||[]){try{const x=await getJson(`${API}/variables/${encodeURIComponent(d.file)}`);const v=(x.variables||[]).find(z=>z.name===name);if(v)catalog.push({...v,file:d.file})}catch{}}}if(!catalog.length)throw Error('No variables returned by backend');renderCatalog();setupDates();const preferred=catalog.find(v=>/temperature|thetao/i.test(`${v.name} ${v.long_name||''} ${v.standard_name||''}`))||catalog[0];await selectVariable(preferred);document.getElementById('loading').style.display='none';setView('3d')}catch(e){document.getElementById('loading').innerHTML=`<div><b>SOLVX</b><small>BACKEND ERROR<br>${e.message}</small></div>`;setStatus('API unavailable')}}
document.getElementById('depth').oninput=e=>{visibleCut=+e.target.value;document.getElementById('depthText').textContent=Math.round(visibleCut*100)+'%';if(volumeMesh)volumeMesh.material.uniforms.uCut.value=visibleCut};document.getElementById('time').oninput=async()=>{updateDate();await loadData()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.getElementById('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();ren.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{if(e.key==='1')setView('3d');if(e.key==='2')setView('top');if(e.key==='3')setView('profile');if(e.key==='4')setView('under');if(e.key.toLowerCase()==='r')setView('3d')});
let t0=performance.now();function animate(){requestAnimationFrame(animate);const t=(performance.now()-t0)*.001;surface.position.z=.5+.7*Math.sin(t*.6);surface.rotation.z=.0005*Math.sin(t*.2);cameraLocal();ctl.update();ren.render(scene,cam)}animate();init();
</script></body></html>'''
    return html.replace('__PAYLOAD__', payload)
