import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as THREE from 'three';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';
const labels={temperature:['Temperature','°C'],salinity:['Salinity','PSU'],currents:['Currents','m/s'],'sea level':['Sea Surface Height','m'],'sea surface temp anamoly':['SST Anomaly','°C'],baymetry:['Bathymetry','m']};
function pretty(v){const k=v.toLowerCase();for(const [key,val] of Object.entries(labels))if(k.includes(key))return val;return [v,'—']}

function Ocean({data,variable,depth,onPoint}){const ref=useRef(),sceneRef=useRef();
 useEffect(()=>{const el=ref.current;const scene=new THREE.Scene();scene.background=new THREE.Color(0x04141f);const camera=new THREE.PerspectiveCamera(45,el.clientWidth/el.clientHeight,.1,5000);camera.position.set(0,-90,125);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);el.appendChild(renderer.domElement);scene.add(new THREE.AmbientLight(0x9bdde8,1.4));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(-100,-150,200);scene.add(light);
 const group=new THREE.Group();scene.add(group);let mesh;
 const build=(p)=>{if(mesh){group.remove(mesh);mesh.geometry.dispose();mesh.material.dispose()} if(!p?.data||!p.shape)return;const dims=p.dimensions.map(String),shape=p.shape.map(Number),xi=dims.findIndex(x=>x.toLowerCase().includes('longitude')),yi=dims.findIndex(x=>x.toLowerCase().includes('latitude')),zi=dims.findIndex(x=>x.toLowerCase().includes('depth'));if(xi<0||yi<0)return;const nx=shape[xi],ny=shape[yi],nz=zi>=0?shape[zi]:1;const flat=[];const walk=(n)=>Array.isArray(n)?n.forEach(walk):flat.push(Number(n));walk(p.data);const vals=flat.filter(Number.isFinite);if(!vals.length)return;let min=Math.min(...vals),max=Math.max(...vals);const pos=[],colors=[],indices=[];const at=(x,y,z)=>{let a=p.data;const ids=[];for(let d=0;d<dims.length;d++){const name=dims[d].toLowerCase();if(d===xi)ids.push(x);else if(d===yi)ids.push(y);else if(d===zi)ids.push(z);else ids.push(0)}for(const i of ids){if(!Array.isArray(a))return NaN;a=a[i]}return Number(a)};const z=Math.min(nz-1,Math.max(0,Math.floor((1-depth)*(nz-1))));for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const v=at(x,y,z),t=Number.isFinite(v)?(v-min)/Math.max(max-min,1e-9):0;pos.push((x/(nx-1)-.5)*180,(y/(ny-1)-.5)*100,(Number.isFinite(v)?t:0)*18);const c=new THREE.Color();c.setHSL(.68-.65*t,.85,.48);colors.push(c.r,c.g,c.b)}for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const a=y*nx+x,b=a+1,c=a+nx,d=c+1;indices.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setIndex(indices);g.computeVertexNormals();mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.72,metalness:.05,side:THREE.DoubleSide}));group.add(mesh);sceneRef.current={mesh,min,max};};build(data);
 let down=false,lastX=0,lastY=0;const move=e=>{if(!down)return;group.rotation.z+=(e.clientX-lastX)*.006;group.rotation.x+=(e.clientY-lastY)*.006;lastX=e.clientX;lastY=e.clientY};const wheel=e=>{camera.position.z=Math.max(45,Math.min(500,camera.position.z+e.deltaY*.12))};renderer.domElement.addEventListener('pointerdown',e=>{down=true;lastX=e.clientX;lastY=e.clientY});window.addEventListener('pointerup',()=>down=false);window.addEventListener('pointermove',move);renderer.domElement.addEventListener('wheel',wheel,{passive:true});const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};window.addEventListener('resize',resize);let raf;const loop=()=>{raf=requestAnimationFrame(loop);group.rotation.y+=.0008;renderer.render(scene,camera)};loop();return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('pointermove',move);renderer.domElement.remove();renderer.dispose()};},[data]);
 return <div className="viewport" ref={ref}/>}

function App(){const [datasets,setDatasets]=useState([]),[vars,setVars]=useState([]),[selected,setSelected]=useState(null),[payload,setPayload]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[depth,setDepth]=useState(1),[view,setView]=useState('3D');
 useEffect(()=>{fetch(API+'/datasets').then(r=>r.json()).then(x=>{setDatasets(x.datasets||x);setLoading(false)}).catch(e=>{setError('Cannot connect to SolvX API');setLoading(false)})},[]);
 useEffect(()=>{if(!datasets.length)return;const file=datasets[0].filename||datasets[0].file||datasets[0].name; if(!file)return;fetch(API+'/variables/'+encodeURIComponent(file)).then(r=>r.json()).then(x=>{const list=x.variables||x;setVars(Array.isArray(list)?list:Object.keys(list||{}));if(!selected&&Array.isArray(list)&&list[0])setSelected({file,variable:list[0]})}).catch(()=>{})},[datasets]);
 useEffect(()=>{if(!selected)return;setLoading(true);const q=new URLSearchParams({file:selected.file,variable:selected.variable,lat_min:'16.07',lat_max:'23.52',lon_min:'84.10',lon_max:'92.99',depth_min:'0',depth_max:'5000'});fetch(API+'/data/region/array?'+q).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setPayload).catch(()=>setError('Unable to load selected ocean field')).finally(()=>setLoading(false))},[selected]);
 const [name,unit]=selected?pretty(selected.variable):['Ocean variable','—'];
 return <main><header><div><strong>SOLVX</strong><span>BAY OF BENGAL · LIVE OCEAN EXPLORER</span></div><div className="views">{['3D','TOP','PROFILE','UNDER'].map(v=><button className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</div></header><aside><div className="eyebrow">OCEAN VARIABLES</div><section className="activeVar"><b>{name}</b><small>{selected?.variable||'Loading variables'} · {unit}</small></section><div className="list">{vars.map(v=>{const [l,u]=pretty(v);return <button className={selected?.variable===v?'sel':''} onClick={()=>setSelected({file:selected.file,variable:v})}><span>{l}</span><small>{u}</small></button>})}</div><div className="divider"/><div className="eyebrow">DEPTH</div><input type="range" min="0" max="1" step=".01" value={depth} onChange={e=>setDepth(+e.target.value)}/><div className="rangeLabel"><span>Surface</span><span>{Math.round(depth*100)}%</span></div></aside><div className="status">{error|| (loading?'Loading ocean data…':`API connected · ${datasets.length} dataset(s)`)}</div><div className="legend"><b>{name}</b><span>{unit}</span><div className="gradient"/><small>low <i>field value</i> high</small></div>{payload?<Ocean data={payload} variable={selected?.variable} depth={depth}/>:<div className="empty">{loading?'CONNECTING TO OCEAN DATA':'No field loaded'}</div>}<footer><span>TIME</span><input type="range" min="0" max="0" defaultValue="0"/><b>Live dataset</b></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);